[workspace]
members = ["sw-cli-macros", "examples/demo-cli", "examples/build-config-dispatch-demo", "examples/working-cli-demo"]
resolver = "2"

[package]
name = "sw-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
sw-cli-macros = { path = "sw-cli-macros" }
chrono = "0.4"
