[package]
name = "demo-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/softwarewrighter/sw-cli"

[lints]
workspace = true

[dependencies]
sw-cli = { path = "../.." }

[build-dependencies]
sw-cli = { path = "../.." }
